interface License {
  name: string;
  creator: string;
  year: string;
  licenseType: string;
  description?: string;
  repository?: string;
  licenseUrl?: string;
  licenseText?: string;
}

const licenses: License[] = [
  {
    name: "Next.js",
    creator: "Vercel",
    year: "2023",
    licenseType: "MIT",
    description: "The React Framework for the Web",
    repository: "https://github.com/vercel/next.js",
    licenseUrl: "https://github.com/vercel/next.js/blob/canary/license.md",
  },
  {
    name: "React",
    creator: "Meta",
    year: "2023",
    licenseType: "MIT",
    description: "A JavaScript library for building user interfaces",
    repository: "https://github.com/facebook/react",
    licenseUrl: "https://github.com/facebook/react/blob/main/LICENSE",
  },
  {
    name: "@radix-ui/react-dialog",
    creator: "Radix UI",
    year: "2023",
    licenseType: "MIT",
    description: "Accessible React Dialog Components",
    repository: "https://github.com/radix-ui/primitives",
    licenseUrl: "https://github.com/radix-ui/primitives/blob/main/LICENSE",
  },
  {
    name: "@radix-ui/react-label",
    creator: "Radix UI",
    year: "2023",
    licenseType: "MIT",
    description: "Accessible React Label Components",
    repository: "https://github.com/radix-ui/primitives",
    licenseUrl: "https://github.com/radix-ui/primitives/blob/main/LICENSE",
  },
  {
    name: "@radix-ui/react-popover",
    creator: "Radix UI",
    year: "2023",
    licenseType: "MIT",
    description: "Accessible React Popover Components",
    repository: "https://github.com/radix-ui/primitives",
    licenseUrl: "https://github.com/radix-ui/primitives/blob/main/LICENSE",
  },
  {
    name: "@radix-ui/react-progress",
    creator: "Radix UI",
    year: "2023",
    licenseType: "MIT",
    description: "Accessible React Progress Components",
    repository: "https://github.com/radix-ui/primitives",
    licenseUrl: "https://github.com/radix-ui/primitives/blob/main/LICENSE",
  },
  {
    name: "@radix-ui/react-radio-group",
    creator: "Radix UI",
    year: "2023",
    licenseType: "MIT",
    description: "Accessible React Radio Group Components",
    repository: "https://github.com/radix-ui/primitives",
    licenseUrl: "https://github.com/radix-ui/primitives/blob/main/LICENSE",
  },
  {
    name: "@radix-ui/react-scroll-area",
    creator: "Radix UI",
    year: "2023",
    licenseType: "MIT",
    description: "Accessible React Scroll Area Components",
    repository: "https://github.com/radix-ui/primitives",
    licenseUrl: "https://github.com/radix-ui/primitives/blob/main/LICENSE",
  },
  {
    name: "@radix-ui/react-select",
    creator: "Radix UI",
    year: "2023",
    licenseType: "MIT",
    description: "Accessible React Select Components",
    repository: "https://github.com/radix-ui/primitives",
    licenseUrl: "https://github.com/radix-ui/primitives/blob/main/LICENSE",
  },
  {
    name: "@radix-ui/react-separator",
    creator: "Radix UI",
    year: "2023",
    licenseType: "MIT",
    description: "Accessible React Separator Components",
    repository: "https://github.com/radix-ui/primitives",
    licenseUrl: "https://github.com/radix-ui/primitives/blob/main/LICENSE",
  },
  {
    name: "@radix-ui/react-slider",
    creator: "Radix UI",
    year: "2023",
    licenseType: "MIT",
    description: "Accessible React Slider Components",
    repository: "https://github.com/radix-ui/primitives",
    licenseUrl: "https://github.com/radix-ui/primitives/blob/main/LICENSE",
  },
  {
    name: "@radix-ui/react-slot",
    creator: "Radix UI",
    year: "2023",
    licenseType: "MIT",
    description: "Accessible React Slot Components",
    repository: "https://github.com/radix-ui/primitives",
    licenseUrl: "https://github.com/radix-ui/primitives/blob/main/LICENSE",
  },
  {
    name: "@radix-ui/react-switch",
    creator: "Radix UI",
    year: "2023",
    licenseType: "MIT",
    description: "Accessible React Switch Components",
    repository: "https://github.com/radix-ui/primitives",
    licenseUrl: "https://github.com/radix-ui/primitives/blob/main/LICENSE",
  },
  {
    name: "@radix-ui/react-tooltip",
    creator: "Radix UI",
    year: "2023",
    licenseType: "MIT",
    description: "Accessible React Tooltip Components",
    repository: "https://github.com/radix-ui/primitives",
    licenseUrl: "https://github.com/radix-ui/primitives/blob/main/LICENSE",
  },
  {
    name: "class-variance-authority",
    creator: "Level Up Labs",
    year: "2023",
    licenseType: "MIT",
    description: "A utility for managing class variance in CSS",
    repository: "https://github.com/joe-bell/class-variance-authority",
    licenseUrl:
      "https://github.com/joe-bell/class-variance-authority/blob/main/LICENSE",
  },
  {
    name: "clsx",
    creator: "Jared Palmer",
    year: "2023",
    licenseType: "MIT",
    description:
      "A tiny utility for constructing `className` strings conditionally",
    repository: "https://github.com/lukeed/clsx",
    licenseUrl: "https://github.com/lukeed/clsx/blob/main/LICENSE",
  },
  {
    name: "framer-motion",
    creator: "Framer",
    year: "2023",
    licenseType: "MIT",
    description: "A production-ready motion library for React",
    repository: "https://github.com/framer/motion",
    licenseUrl: "https://github.com/framer/motion/blob/main/LICENSE",
  },
  {
    name: "lucide-react",
    creator: "Lucide",
    year: "2023",
    licenseType: "MIT",
    description: "A set of beautifully designed open-source icons for React",
    repository: "https://github.com/lucide-icons/lucide",
    licenseUrl: "https://github.com/lucide-icons/lucide/blob/main/LICENSE",
  },
  {
    name: "tailwind-merge",
    creator: "Wolfr",
    year: "2023",
    licenseType: "MIT",
    description: "Utility to merge Tailwind CSS class names",
    repository: "https://github.com/dcastil/tailwind-merge",
    licenseUrl: "https://github.com/dcastil/tailwind-merge/blob/main/LICENSE",
  },
  {
    name: "tailwindcss-animate",
    creator: "Tailwind Labs",
    year: "2023",
    licenseType: "MIT",
    description: "Animated utilities for Tailwind CSS",
    repository: "https://github.com/benface/tailwindcss-animate",
    licenseUrl:
      "https://github.com/benface/tailwindcss-animate/blob/main/LICENSE",
  },
  {
    name: "react-dom",
    creator: "Meta",
    year: "2023",
    licenseType: "MIT",
    description: "Entry point to the DOM and server renderers for React",
    repository: "https://github.com/facebook/react",
    licenseUrl: "https://github.com/facebook/react/blob/main/LICENSE",
  },
  {
    name: "typescript",
    creator: "Microsoft",
    year: "2023",
    licenseType: "Apache-2.0",
    description: "A superset of JavaScript that adds static typing",
    repository: "https://github.com/microsoft/TypeScript",
    licenseUrl: "https://github.com/microsoft/TypeScript/blob/main/LICENSE.txt",
  },
  {
    name: "@types/node",
    creator: "DefinitelyTyped",
    year: "2023",
    licenseType: "MIT",
    description: "TypeScript definitions for Node.js",
    repository: "https://github.com/DefinitelyTyped/DefinitelyTyped",
    licenseUrl:
      "https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/LICENSE",
  },
  {
    name: "@types/react",
    creator: "DefinitelyTyped",
    year: "2023",
    licenseType: "MIT",
    description: "TypeScript definitions for React",
    repository: "https://github.com/DefinitelyTyped/DefinitelyTyped",
    licenseUrl:
      "https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/LICENSE",
  },
  {
    name: "@types/react-dom",
    creator: "DefinitelyTyped",
    year: "2023",
    licenseType: "MIT",
    description: "TypeScript definitions for React DOM",
    repository: "https://github.com/DefinitelyTyped/DefinitelyTyped",
    licenseUrl:
      "https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/LICENSE",
  },
  {
    name: "eslint",
    creator: "ESLint Team",
    year: "2023",
    licenseType: "MIT",
    description: "A pluggable linting utility for JavaScript and JSX",
    repository: "https://github.com/eslint/eslint",
    licenseUrl: "https://github.com/eslint/eslint/blob/main/LICENSE.md",
  },
  {
    name: "eslint-config-next",
    creator: "Vercel",
    year: "2023",
    licenseType: "MIT",
    description: "ESLint configuration for Next.js projects",
    repository: "https://github.com/vercel/next.js",
    licenseUrl: "https://github.com/vercel/next.js/blob/canary/LICENSE",
  },
  {
    name: "postcss",
    creator: "PostCSS",
    year: "2023",
    licenseType: "MIT",
    description: "A tool for transforming CSS with JavaScript",
    repository: "https://github.com/postcss/postcss",
    licenseUrl: "https://github.com/postcss/postcss/blob/main/LICENSE",
  },
  {
    name: "tailwindcss",
    creator: "Tailwind Labs",
    year: "2023",
    licenseType: "MIT",
    description:
      "A utility-first CSS framework for rapidly building custom designs",
    repository: "https://github.com/tailwindlabs/tailwindcss",
    licenseUrl:
      "https://github.com/tailwindlabs/tailwindcss/blob/master/LICENSE",
  },
];

export default licenses;
export type { License };
